nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.9.2.cjs
packageExtensions:
  "@sentry/nextjs@*":
    peerDependencies:
      next: "*"
      react: "*"
      react-dom: "*"
    peerDependenciesMeta:
      react:
        optional: false
      react-dom:
        optional: false
  "@sentry/opentelemetry@*":
    dependencies:
      "@opentelemetry/api": ^1.0.0
      "@opentelemetry/core": ^1.0.0
      "@opentelemetry/sdk-trace-base": ^1.0.0
      "@opentelemetry/semantic-conventions": ^1.0.0
  "@sentry/react@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  next@*:
    peerDependencies:
      "@next/bundle-analyzer": "*"
      "@sentry/nextjs": "*"
      pnp-webpack-plugin: "*"
  tunnel-rat@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@tanstack/router-devtools-core@*":
    dependencies:
      tiny-invariant: "*"
      "@tanstack/router-core": "*"
  "tsr@*":
    dependencies:
      typescript: "*"
