nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.9.2.cjs
packageExtensions:
  "next@*":
    peerDependencies:
      "@sentry/nextjs": "*"
  "@sentry/opentelemetry@*":
    dependencies:
      "@opentelemetry/api": "^1.0.0"
      "@opentelemetry/core": "^1.0.0"
      "@opentelemetry/sdk-trace-base": "^1.0.0"
      "@opentelemetry/semantic-conventions": "^1.0.0"
  "@sentry/react@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@sentry/nextjs@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
      next: "*"
    peerDependenciesMeta:
      react:
        optional: false
      react-dom:
        optional: false
