version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: https://dev.kokomen.kr
        NEXT_PUBLIC_API_BASE_URL: https://api-dev.kokomen.kr/api/v1
        NEXT_PUBLIC_V2_API_BASE_URL: https://api-dev.kokomen.kr/api/v2
        NEXT_PUBLIC_NOTIFICATION_API_BASE_URL: https://notification-api-dev.kokomen.kr/api/v1
        NEXT_PUBLIC_V3_API_BASE_URL: https://api-dev.kokomen.kr/api/v3
        NEXT_PUBLIC_GRAPHQL_URL: https://api-dev.kokomen.kr/api/v3/graphql
        NEXT_PUBLIC_POSTHOG_KEY: ${NEXT_PUBLIC_POSTHOG_KEY}
        NEXT_PUBLIC_POSTHOG_HOST: ${NEXT_PUBLIC_POSTHOG_HOST}
        NEXT_PUBLIC_CDN_BASE_URL: ${DEV_CDN_BASE_URL}
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
      - NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - NEXT_PUBLIC_CDN_BASE_URL=${DEV_CDN_BASE_URL}
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    container_name: kokomen-client
    expose:
      - "3000"
    restart: always
    networks:
      - dev-kokomen-net

  nginx:
    image: nginx:latest
    container_name: kokomen-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - client
    restart: always
    networks:
      - dev-kokomen-net
