services:
  kokomen-nest-server-dev:
    build:
      context: .
      dockerfile: ./apps/kokomen-server/Dockerfile
    environment:
      TZ: Asia/Seoul
      NODE_ENV: development
      DATABASE_HOST: ${DATABASE_HOST_DEV}
      DATABASE_PORT: 3306
      DATABASE_USERNAME: ${DATABASE_USERNAME_DEV}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD_DEV}
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD_DEV}
      DATABASE_DATABASE: kokomen-dev
      REDIS_HOST: ${REDIS_HOST_DEV}
      REDIS_PORT: 6379
      PORT: 3000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REFION: ap-northeast-2
      AWS_BEDROCK_RESUME_EVALUATION_FLOW_ID: ${AWS_BEDROCK_RESUME_EVALUATION_FLOW_ID}
      AWS_BEDROCK_RESUME_EVALUATION_FLOW_ALIAS_ID: ${AWS_BEDROCK_RESUME_EVALUATION_FLOW_ALIAS_ID}
    container_name: kokomen-nest-server-dev
    restart: on-failure:3
    ports:
      - "3000:3000"
      - "3001:3001"

  nginx:
    image: nginx:alpine
    container_name: kokomen-nest-nginx-dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/kokomen-server/nginx/dev/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kokomen-nest-server-dev
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
