version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    container_name: kokomen-client
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    image: nginx:latest
    container_name: kokomen-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - client
    restart: always
