name: "🐞 Bug"
description: "버그를 기록하고 추적합니다."
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: 무슨 일이 있었나?
      description: 버그 현상을 간단히 적어두기
      placeholder: 예) 페이지가 새로고침되면 다크모드 설정이 풀림
    validations:
      required: true

  - type: textarea
    id: cause
    attributes:
      label: 원인 (알고 있다면)
      description: "원인을 알고 있다면 적어두기 (디버깅 로그 등)"
      placeholder: 예) localStorage가 초기화되는 듯
    validations:
      required: false

  - type: textarea
    id: fix-idea
    attributes:
      label: 고칠 아이디어 / TODO
      description: "어떻게 고칠지 간단히 적어두기"
      placeholder: 예) mount 시 localStorage에서 테마 읽어서 반영
    validations:
      required: false

  - type: input
    id: timestamp
    attributes:
      label: 기록한 날짜
      description: "오늘 날짜 입력 (자동 기록 안됨)"
      placeholder: "2025-07-05"
    validations:
      required: false
