version: "3.8"

services:
  client-blue:
    image: ${DOCKER_USERNAME}/kokomen-client-prod:production
    container_name: kokomen-client-blue
    expose:
      - "3000"
    restart: always
    profiles:
      - blue

  client-green:
    image: ${DOCKER_USERNAME}/kokomen-client-prod:production
    container_name: kokomen-client-green
    expose:
      - "3000"
    restart: always
    profiles:
      - green

  ats:
    image: trafficserver/trafficserver
    container_name: kokomen-ats
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../trafficserver/prod:/opt/etc/trafficserver
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    restart: always
