nodeLinker: node-modules
enableGlobalCache: false
packageExtensions:
  "@invertase/react-native-apple-authentication@*":
    dependencies:
      "prop-types": "^15.5.10"
  "@apollo/client@*":
    dependencies:
      "rxjs": "^7.3.0"
