name: Test Workflow
on:
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_BASE_URL: https://api-dev.kokomen.kr/api/v1
      NEXT_PUBLIC_BASE_URL: https://localhost:3000
      NEXT_PUBLIC_NOTIFICATION_API_BASE_URL: https://notification.kokomen.kr/api/v1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: "Install dependencies"
        run: |
          corepack enable
          yarn install --immutable

      - name: Type build
        run: |
          yarn types:build

      - name: Run tests
        run: yarn test
